## Domain

Our domain of interest is social media. We’re interested in this domain because social media consumption behaviors could help us understand what makes people follow certain social media pages or trends more over the others. This information could help future creators and marketers strategize better ideas and plans during the content creation process. We hope to uncover what elements of a social media page lead to more engagement, what trends are more likely to be popular, and how social media usage varies amongst different groups.

## Data

We found the data set we used, Social Influence on Shopping, on a site called data.world. This data was collected by a team led by Adam Halper using their social survey mobile platform Whatsgoodly. They have over 300,000 millenial and Gen Z members and garnered over 150 million survey responses from this demographic to date. This data contains 1450 observations and 6 features.

## Summary Information

The dataset collected information on which social media platform influenced people's online shopping the most. In our summary information script, we made a list of how many people felt most influenced by each social media platform.

```{r, echo = FALSE}
library(knitr)
my_dataframe <- whatsgoodlydata_6

library(tidyverse)

summary_info <- list()
#Number of features (columns)
summary_info$num_features <- ncol(my_dataframe) 
#Number of different social media platforms as answer choices
summary_info$num_socials <- length(unique(my_dataframe[["answer"]]))

#Number most influenced by Facebook 
summary_info$num_facebook <- my_dataframe %>% 
  filter(answer == "Facebook") %>%
  summarize(sum_facebook = sum(count, na.rm = FALSE)) %>%
  pull(sum_facebook)

#Number most influenced by Instagram 
summary_info$num_instagram <- my_dataframe %>% 
  filter(answer == "Instagram") %>%
  summarize(sum_instagram = sum(count, na.rm = FALSE)) %>%
  pull(sum_instagram)

#Number most influenced by Snapchat 
summary_info$num_snapchat <- my_dataframe %>% 
  filter(answer == "Snapchat") %>%
  summarize(sum_snapchat = sum(count, na.rm = FALSE)) %>%
  pull(sum_snapchat)

#Number most influenced by Twitter
summary_info$num_twitter <- my_dataframe %>% 
  filter(answer == "Twitter") %>%
  summarize(sum_twitter = sum(count, na.rm = FALSE)) %>%
  pull(sum_twitter)

#Number most influenced by none 
summary_info$num_none <- my_dataframe %>% 
  filter(answer == "None") %>%
  summarize(sum_none = sum(count, na.rm = FALSE)) %>%
  pull(sum_none)

```
`r summary_info`

